config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'home#index'
  resources :players, only: [:new, :create, :update, :edit]
  resources :player_profiles, only: [:new, :create, :show, :index, :edit, :update]
  resources :coach_profiles, only: [:new, :create, :show, :index]

  resources :recruiters, only: [:new, :create, :update]
  resources :recruiter_profiles, only: [:new, :create, :show, :index]
  resources :dashboard, only: [:index]

  resources :users, only: [:index]

  get '/auth/facebook/callback', to: 'oauth#create'
  get 'auth/failure', to: redirect('/')

  get '/auth/twitter/callback', to: 'oauth#create'
  get '/auth/twitter', as: :twitter_login
  resources :favorite_players, only: [:create, :new]

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :type_selection, only: [:new, :create]

  namespace :users do
    get '/:id/favorite_player', to: 'favorite_player#create'
  end

  namespace :teams do
    get '/:id/stats', to: 'stats#index'
  end

  get  '/:id/favorite_player', to: 'favorite_player#create'
  get  '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get  '/logout', to: 'sessions#destroy'
  post '/send_text', to: 'twilio#create'
  post '/receive_text', to: 'twilio#update'

  post '/watch_list/:id', to: 'prospects#create', as: :create_watch_list
  delete '/watch_list/:id', to: 'prospects#destroy', as: :delete_watch_list


  resources :uploads, only: [:create]

  # internal api
  namespace :api do
    namespace :v1 do
      get 'locations', to: "locations#index"
      get 'players/stats', to: 'player_stats#show'
      get 'players/points', to: 'player_points#show'
    end
  end



end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    redirect_to login_path if current_user.nil?
    @tweet_info = build_twitter_service
    if current_user.class == "Player" && current_user.favorite_player
      raw_data = build_mysportsfeeds_service.data
      @favorite_player_stats = FavoritePlayerStats.new(raw_data)
    end
  end

  private

  def build_twitter_service
    @service ||= TwitterService.new(current_user)
  end

  def build_mysportsfeeds_service
    @sports_feeds_service ||= MySportsFeedsService.new(current_user.favorite_player.full_name)
  end

end

app/views/dashboard/_admin.html.erb
<h1><%= "Hello #{current_user.first_name}" %></h1>

app/views/dashboard/_coach.html.erb
<div class="container">
  <div class="col-md-4">
    <img class="profile-pic" src="https://media.licdn.com/media-proxy/ext?w=800&h=800&hash=o6u9Tq%2FiOJm8OxArAcTdAq%2Fy5Lk%3D&ora=1%2CaFBCTXdkRmpGL2lvQUFBPQ%2CxAVta5g-0R69hAxU0Rks6bmIpkb-50hKCoTTEHX8RHTuvoTTOCq8J4OcZuH--hlDJmgewUB2LrzwHWW_VtCjKoPteN0lipPtLJHjNVBROlE8gG9JodY6NRUropW_SPj5bCdN3eIVbj24Mq3gaFwsRy8n-g" alt="">
  </div>
  <div class="col-md-8">
    <ul>
      <h3>Coach <%= current_user.last_name %>'s Dashboard</h3><br>
      <p>Institution: <%= current_user.profile.institution %></p>
      <p>Current Teams: </p>
      <% current_user.teams.each do |team| %>
        <ul>
          <li><%= team.name %></li>
        </ul>
      <% end %>
      <p>Email: <%= current_user.profile.email %></p>
      <p>Phone: <%= current_user.profile.phone_number %></p>
      <br><br><br>
      <h4>Upload CSV for game stats:</h4>
      <%= form_tag uploads_path, multipart: true do %>
        <%= file_field_tag :file %>
        <%= submit_tag "Upload CSV", :class => 'btn btn-warning start-rec' %>
      <% end %>
    </ul>
  </div>
</div>

<div class="container">
  <div class="col-md-12 prf-sum">
    <br>
    <h3> Your Teams </h3>
    <ul class="nav nav-tabs">
      <li class="active"><a href="#">Teams</a></li>
        <% current_user.teams.each do |team| %>
          <li><%= link_to team.name, "##{team.name}", "data-toggle" => "tab" %></li>
        <% end %>
    </ul>

        <div class="tab-content">
          <% current_user.teams.each do |team| %>
            <% team.players.each do |player| %>
              <div id="#">

              </div>
          <table class="prospect-table">
              <tr>
                <th>Name</th>
                <th>Grade Level</th>
              </tr>
              <tr>
                <td><%= link_to player.name, player_profile_path(player.profile)%></td>
                <td><%= player.profile.grade_level %></td>
              </tr>
            <% end %>
          </table>
      <% end %>
      </div>
    </ul>
  </div>
</div>

app/views/dashboard/_player.html.erb
<div class="container">
  <div class="col-md-4">
    <img class="profile-pic" src="https://media.licdn.com/media-proxy/ext?w=800&h=800&hash=o6u9Tq%2FiOJm8OxArAcTdAq%2Fy5Lk%3D&ora=1%2CaFBCTXdkRmpGL2lvQUFBPQ%2CxAVta5g-0R69hAxU0Rks6bmIpkb-50hKCoTTEHX8RHTuvoTTOCq8J4OcZuH--hlDJmgewUB2LrzwHWW_VtCjKoPteN0lipPtLJHjNVBROlE8gG9JodY6NRUropW_SPj5bCdN3eIVbj24Mq3gaFwsRy8n-g" alt="">
  </div>
  <div class="col-md-8">
    <ul>
      <h3><%= current_user.name %>'s Dashboard</h3><br>
      <h3><%= link_to "Edit Profile", edit_player_profile_path(current_user) %></h3>
      <p>School: <%= current_user.profile.school %></p>
      <p> Grade: <%= current_user.profile.grade_level %></p>
      <p>   GPA: <%= current_user.profile.gpa %></p>
      <p>Guardian's Phone: <%= current_user.profile.guardian_phone %></p>
      <br><br>
      <table class="prospect-table">
        <tr>
          <th>Height</th>
          <th>Weight</th>
          <th>Total Points</th>
          <th>Total Fouls</th>
        </tr>
        <tr>
          <td><%= current_user.profile.height %></td>
          <td><%= current_user.profile.weight %></td>
          <td><%= PlayerStat.player_total_points(current_user) %></td>
          <td><%= PlayerStat.player_total_fouls(current_user) %></td>
        </tr>
      </table>
    </ul>
  </div>
</div>

<div class="container">
  <div class="col-md-6 prf-sum">
    <br>
    <% if current_user.favorite_player.nil? %>
      <h5><%= link_to "Add your favorite player's screename to see recent tweets", new_favorite_player_path %></h5>
    <% else %>
      <h5>Favorite Player: <%= current_user.favorite_player.screen_name %> | <%= link_to "Change your favorite player", new_favorite_player_path %></h5>
      <h5><%= current_user.favorite_player.screen_name %>'s Stats:</h5><br>
      <h5>Their Tweets:</h5><br>
        <% @tweet_info.fav_player_tweets.each do |tweet| %>
          <li><%= tweet.text %></li>
          <br>
        <% end %>
    <% end %>
  </div>
</div>

app/views/dashboard/_recruiter.html.erb
<div class="container">
  <div class="col-md-4">
    <img class="profile-pic" src="https://media.licdn.com/media-proxy/ext?w=800&h=800&hash=o6u9Tq%2FiOJm8OxArAcTdAq%2Fy5Lk%3D&ora=1%2CaFBCTXdkRmpGL2lvQUFBPQ%2CxAVta5g-0R69hAxU0Rks6bmIpkb-50hKCoTTEHX8RHTuvoTTOCq8J4OcZuH--hlDJmgewUB2LrzwHWW_VtCjKoPteN0lipPtLJHjNVBROlE8gG9JodY6NRUropW_SPj5bCdN3eIVbj24Mq3gaFwsRy8n-g" alt="">
  </div>
  <div class="col-md-8">
    <ul>
      <h3><%= current_user.name %>'s Dashboard</h3><br>
      <p>Representing: <%= current_user.profile.institution %></p>
      <p>Email: <%= current_user.profile.email %></p>
      <p>Phone: <%= current_user.profile.phone_number %></p>
    </ul>
  </div>
</div>

<div class="container">
  <div class="col-md-12 prf-sum">
    <br>
    <h3><%= current_user.prospects.count %> Potential Recruit(s) </h3>
    <table class="prospect-table">
      <tr>
        <th>Name</th>
        <th>School</th>
        <th>Team</th>
        <th>Grade Level</th>
        <th>Status</th>
        <th>Next Game</th>
        <th>Hot?</th>
      </tr>
      <% current_user.prospects.each do |prospect| %>
        <tr>
          <td><%= link_to prospect.name, player_profile_path(prospect.player_profile)%></td>
          <td><%= prospect.player_profile.school %></td>
          <td><%= prospect.player_profile.player.teams.first.name %></td>
          <td><%= prospect.player_profile.grade_level %></td>
          <% if prospect.status == "watching" %>
          <td><%= link_to "Remove from Watchlist", delete_watch_list_path(prospect.id), method: :delete, class: "btn btn-danger btn-sm" %></td>
          <% else %>
            <td><%= prospect.status %></td>
          <% end %>
          <td><%= prospect.player_profile.player.upcoming.first.when %></td>
          <td> <% if prospect.player_profile.player.hot? %>
            <%= image_tag 'fire_icon.jpg', size: "25x25" %>
          <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/dashboard/index.html.erb
<% if current_user.type == "Recruiter" %>
  <%= render partial: 'dashboard/recruiter' %>
<% elsif current_user.type == 'Player' %>
  <%= render partial: 'dashboard/player' %>
<% elsif current_user.type == "Coach" %>
  <%= render partial: 'dashboard/coach' %>
<% else %>
  <%= render partial: 'dashboard/admin' %>
<% end %>