config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'home#index'
  resources :players, only: [:new, :create, :update, :edit]
  resources :player_profiles, only: [:new, :create, :show, :index, :edit, :update]
  resources :coach_profiles, only: [:new, :create, :show, :index]

  resources :recruiters, only: [:new, :create, :update]
  resources :recruiter_profiles, only: [:new, :create, :show, :index]
  resources :dashboard, only: [:index]

  resources :users, only: [:index]

  get '/auth/facebook/callback', to: 'oauth#create'
  get 'auth/failure', to: redirect('/')

  get '/auth/twitter/callback', to: 'oauth#create'
  get '/auth/twitter', as: :twitter_login
  resources :favorite_players, only: [:create, :new]

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :type_selection, only: [:new, :create]

  namespace :users do
    get '/:id/favorite_player', to: 'favorite_player#create'
  end

  namespace :teams do
    get '/:id/stats', to: 'stats#index'
  end

  get  '/:id/favorite_player', to: 'favorite_player#create'
  get  '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get  '/logout', to: 'sessions#destroy'
  post '/send_text', to: 'twilio#create'
  post '/receive_text', to: 'twilio#update'

  post '/watch_list/:id', to: 'prospects#create', as: :create_watch_list
  delete '/watch_list/:id', to: 'prospects#destroy', as: :delete_watch_list


  resources :uploads, only: [:create]

  # internal api
  namespace :api do
    namespace :v1 do
      get 'locations', to: "locations#index"
      get 'players/stats', to: 'player_stats#show'
      get 'players/points', to: 'player_points#show'
    end
  end



end

app/models/coach_profile.rb
class CoachProfile < ApplicationRecord
  belongs_to :user
end

app/controllers/coach_profiles_controller.rb
class CoachProfilesController < ApplicationController
  before_action :player_check

  def new
    @coach_id = current_user.id
    @coach_profile = CoachProfile.new
  end

  def create
    @coach_profile = CoachProfile.create(coach_params)
    if @coach_profile.save
      redirect_to dashboard_index_path
    else
      flash[:message] = "There was an error processing your request; please try again"
      render :new
    end
  end

  def show
    @coach_profile = CoachProfile.find(params[:id])
    @images = Image.random_user
  end

  def index
    @coach_profiles = CoachProfile.page(params[:page]).per(30)
  end

  private

  def coach_params
    params.require(:coach_profile).permit(:first_name, :last_name, :institution, :email, :phone_number, :coach_id)
  end

  def player_check
    flash[:message] = "Please login to view coach pages."
    redirect_to login_path if current_user.nil? || current_user.type == "Player"
  end

end

app/views/coach_profiles/_coach_profile.html.erb
<div class="col-md-1"></div>
<div class="col-md-3">
  <div class="card">
    <div class="card-block">
      <h3><%= link_to coach_profile.coach.name, coach_profile_path(coach_profile.id)
               %></h3>
    </div>
  </div>
</div>

app/views/coach_profiles/index.html.erb
<div class="container">
  <div class="border-for-index">
    <h1 align="center">All Coaches</h1>
  </div>
  <br>
  <div class="border-for-index">

    <div class="row" id="coach_profiles">
      <%= render @coach_profiles %>
    </div>
  </div>

    <div align="center" id="paginator">
      <%= paginate @coach_profiles, remote: true %>
    </div>
</div>

app/views/coach_profiles/index.js.erb
$('#coach_profiles').html('<%= escape_javascript render(@coach_profiles) %>');
$('#paginator').html('<%= escape_javascript(paginate(@coach_profiles, remote: true).to_s) %>');

app/views/coach_profiles/new.html.erb
<div class="container text-center">

<h1>Fill Out Profile</h1>

<%= form_for @coach_profile do |f| %>

  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <%= f.label :institution %>
  <%= f.text_field :institution %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>

  <%= f.hidden_field :coach_id, value: @coach_id %>

  <%= f.submit "Create Profile" %>

<% end %>
</div>

app/views/coach_profiles/show.html.erb
<div class="container profile-body">
  <div class="container">
    <div class="row">
      <div class="col-md-8 column-border">
        <div class="image">
          <h3><%= image_tag @images.sample.picture, size: "150x150", class: 'img-circle', style: "border: 1px solid;" %>&emsp;<%= @coach_profile.coach.first_name %> <%=@coach_profile.coach.last_name  %> | Coach</h3>
        </div>
      <br>

        <ul lass="list-group">
          <li class="list-group-item">Representing: <%= @coach_profile.institution %></li>
          <li class="list-group-item">Email: <%= @coach_profile.email %></li>
          <li class="list-group-item">Phone: <%= @coach_profile.phone_number %></li>
        </ul>
        <br>
      </div>
    </div>
    </div>
  </div>