config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'home#index'
  resources :players, only: [:new, :create, :update, :edit]
  resources :player_profiles, only: [:new, :create, :show, :index, :edit, :update]
  resources :coach_profiles, only: [:new, :create, :show, :index]

  resources :recruiters, only: [:new, :create, :update]
  resources :recruiter_profiles, only: [:new, :create, :show, :index]
  resources :dashboard, only: [:index]

  resources :users, only: [:index]

  get '/auth/facebook/callback', to: 'oauth#create'
  get 'auth/failure', to: redirect('/')

  get '/auth/twitter/callback', to: 'oauth#create'
  get '/auth/twitter', as: :twitter_login
  resources :favorite_players, only: [:create, :new]

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :type_selection, only: [:new, :create]

  namespace :users do
    get '/:id/favorite_player', to: 'favorite_player#create'
  end

  namespace :teams do
    get '/:id/stats', to: 'stats#index'
  end

  get  '/:id/favorite_player', to: 'favorite_player#create'
  get  '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get  '/logout', to: 'sessions#destroy'
  post '/send_text', to: 'twilio#create'
  post '/receive_text', to: 'twilio#update'

  post '/watch_list/:id', to: 'prospects#create', as: :create_watch_list
  delete '/watch_list/:id', to: 'prospects#destroy', as: :delete_watch_list


  resources :uploads, only: [:create]

  # internal api
  namespace :api do
    namespace :v1 do
      get 'locations', to: "locations#index"
      get 'players/stats', to: 'player_stats#show'
      get 'players/points', to: 'player_points#show'
    end
  end



end

app/models/player.rb
class Player < User
  has_many :team_players
  has_many :teams, through: :team_players
  has_many :team_coaches, through: :teams
  has_many :games, through: :teams
  has_many :coaches, through: :team_coaches
  has_one :profile, class_name: :PlayerProfile, dependent: :destroy
  has_many :player_stats, through: :profile
  has_one :favorite_player, class_name: :FavoritePlayer


  def name
    if self.first_name.nil? || self.last_name.nil?
      self.profile.first_name + " " + self.profile.last_name
    else
      self.first_name + " " + self.last_name
    end
  end

  def school
    self.profile.school
  end

  def height
    self.profile.height
  end

  def weight
    self.profile.weight
  end

  def grade
    self.profile.grade_level
  end

  def gpa
    self.profile.gpa
  end

  def guardian_phone
    self.profile.guardian_phone
  end

  def stats
    self.player_stats
  end

  def points(x = 10)
    Hash[self.stats.map{|stat| stat.stat_dates + "(game:#{stat.id})"}.zip(self.stats.pluck(:points))].to_a.reverse[0..x-1]
  end

  def fouls(x = 10)
    Hash[self.stats.map{|stat| stat.stat_dates + "(game:#{stat.id})"}.zip(self.stats.pluck(:fouls))].to_a.reverse[0..x-1]
  end

  def team
    if self.teams.count == 1
      self.teams.first
    end
  end

  def upcoming
    unless self.teams.count > 1
      self.games.where(status: "upcoming")
    end
  end

  def hot?
    return true if Prospect.where(player_profile_id: self.profile.id).count > 2
  end

end

app/controllers/players/favorite_player_controller.rb
class Players::FavoritePlayerController < ApplicationController
  def create
  end
end

app/controllers/players/player_profile_controller.rb
class PlayerProfileController < ApplicationController

  def new
    @player_id = params["player_id"]
    @player_profile = PlayerProfile.new
  end

  def create
    byebug
  end  

  def show
    @player_profile.find_by(params[:id])
    if current_user.type == "Recruiter"
      @player = current_user.prospects.find_by(player_profile_id: params[:id]).player_profile.player
    else
    end
  end

end

app/views/players/edit.html.erb
<div class="container text-center">

<h1>Edit Your Profile:</h1>
<%= form_for @player_profile do |f| %>
<%= f.label :school%><br>
<%= f.text_field :school%><br>
<%= f.label :height%><br>
<%= f.text_field :height%><br>
<%= f.label :weight%><br>
<%= f.text_field :weight%><br>
<%= f.label :grade_level%><br>
<%= f.text_field :grade_level%><br>
<%= f.label :gpa%><br>
<%= f.text_field :gpa%><br>
<%= f.label :guardian_phone %><br>
<%= f.text_field :guardian_phone %><br>
<%= f.submit "Update Profile"%>
<% end %>

</div>

app/views/players/index.html.erb
<h1>Players#index</h1>
<p>Find me in app/views/players/index.html.erb</p>

app/views/players/new.html.erb
<div class="container text-center">



<h1>Create New Account</h1>

<%= form_for @player do |f| %>
  <br>
  <%= f.label :first_name %><br>
  <%= f.text_field :first_name, id: "first_name" %><br>
  <br>
  <%= f.label :last_name %><br>
  <%= f.text_field :last_name, id: "last_name" %><br>
  <br>
  <%= f.label :username %><br>
  <%= f.text_field :username, id: "username" %><br>
  <br>
  <%= f.label :password %><br>
  <%= f.password_field :password, id: "password" %><br>
  <br>
  <%= f.label :confirmation_password %><br>
  <%= f.password_field :confirmation_password, id: "confirmation_password" %><br>
  <br>
  <%= f.hidden_field :type, value: "Player" %>
  <%= f.hidden_field :uid, value: @uid %>
  <br>
  <%= f.submit "Create Account"%>

<% end %>

</div>

app/views/players/show.html.erb
<div class="container">
  <div class="row">
    <% if @player.id == current_user.id %>
      <div class="col-md-12 welcome-bar">
        <h1>Welcome <%= @player.username.capitalize %></h1>
        <h3 id="id"><%= @player.id %></h3>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div id="ath-profile-id" class="hidden"><%= @player.id %></div>
    <div class="col-md-3 ath-side-bar">
      <div class=col-md-8>
        <%= image_tag("players/bball_prof.png", :id => "ath-profile-pic") %>
      </div>
      <div class="col-md-8">
        <% if current_user.id == @player.id %>
        <%= link_to "Edit Profile", edit_player_path(@player) %>
        <% end %>
        <h3><%= @player.name %></h3>
        <h4><%= @player.school %></h4>
        <h4><%= @player.grade %></h4>
        <h4><%= @player.height %></h4>
        <h4><%= @player.weight %></h4>
        <h4><%= @player.gpa %></h4>
      </div>
    </div>
    <div class="col-md-9 ath-profile-stats">
      <h1>stats</h1>
      <canvas id="ath-profile-stats" width="1000" height="700"></canvas>
      <%= javascript_include_tag "charts/stats.js" %>
    </div>
  </div>
</div>